### ISSUE TITLE
v1.3 not launching on Sonoma

### ISSUE THREAD

**Issue by farookisonfire** [Mnpn/Azayaka#27]
Hi there, I'm seeing the following error when accessing [Azayaka_1.3.zip](https://github.com/Mnpn/Azayaka/releases/download/v1.3/Azayaka_1.3.zip)

<img width="261" alt="image" src="https://github.com/user-attachments/assets/b8bd8bbc-4d7d-432d-b3f1-52b479080fd8">

**Comment by Mnpn** [comment]
Hi! You'll have to right click the app and hit "Open", then allow the app to run from there (if you update to Sequoia, you'll have to go to System Settings > Privacy & Security and click "Open Anyway") - this message appears because I do not pay the yearly fee for the developer programme membership and the app is thus not [notarised](https://developer.apple.com/documentation/security/notarizing-macos-software-before-distribution).

**Comment by farookisonfire** [comment]
thank you 🙏
